### ISSUE TITLE
cargo run results in "build failed"

### ISSUE THREAD

**Issue by LiamHz** [mfs/shady#1]
Heyo, I know this is an old project but I'm getting this error when running `cargo run` for the first time

```
Compiling glium v0.16.0
error: type `color_space::__CGColorSpace` is private

[I removed 56 other error messages here]

error: could not compile `cocoa`
error: build failed
```

I'm not familiar with the Rust ecosystem, is there an easy fix for this?

**Comment by LiamHz** [comment]
I gave [this repo](https://github.com/polyfloyd/shady) a try as well, and I got similar errors. After a bit of digging it looks like this error occurs because I'm on macOS, which doesn't support EGL.

**Comment by mfs** [comment]
Ah, sorry. Not tested on MacOS and yeah it might be out of date. I'll have a look when I get a chance and see if I can update it and test it on Mac OS. Should be able to do this on the weekend.

**Comment by emigr2k1** [comment]
@LiamHz Try my pull request.

**Comment by LiamHz** [comment]
@emigr2k1 Your pull request fixed all my issues, thank you!
